export const dueDateValue = [3, 6, 12];

export const defaultPercent = {
  percentHigh: 0,
  percentMid: 0,
  percentLow: 0,
};

export const defaultPrice = {
  highManPrice: 0,
  highManCount: 0,
  midManPrice: 0,
  midManCount: 0,
  lowManPrice: 0,
  lowManCount: 0,
};

export const exampleManagementChildren = {
  example: [
    {
      seqNo: "d68c80a8-6de6-44e6-a744-fd2c45ce5155",
      name: "sddasfdddasd",
      order: 0,
      isHidden: false,
      price: [
        {
          month: 3,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 6,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 12,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 7,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 8,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 9,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 10,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 11,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 12,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
      ],
      children: [
        {
          name: "ddddddd",
          order: 0,
          seqNo: "e64da15f-31f7-421b-a5ed-0b6affcfb60b",
          children: [],
          isHidden: false,
        },
      ],
    },
    {
      seqNo: "42809c19-34df-4c30-b41f-81c1234f8e32",
      name: "test",
      order: 1,
      isHidden: false,
      price: [
        {
          month: 3,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 6,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 12,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 7,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 8,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 9,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 10,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 11,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 12,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
      ],
      children: [
        {
          name: "test",
          order: 0,
          seqNo: "d54a4b14-f5b8-47a7-9817-d6f380122765",
          children: [],
          isHidden: false,
        },
      ],
    },
  ],
};

export const exampleManagementPriceChildren = {
  example: [
    {
      seqNo: "d68c80a8-6de6-44e6-a744-fd2c45ce5155",
      price: [
        {
          month: 3,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 6,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 12,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 7,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 8,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 9,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 10,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 11,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 12,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
      ],
      children: [
        {
          name: "ddddddd",
          order: 0,
          seqNo: "e64da15f-31f7-421b-a5ed-0b6affcfb60b",
          children: [],
          isHidden: false,
        },
      ],
    },
    {
      seqNo: "42809c19-34df-4c30-b41f-81c1234f8e32",
      price: [
        {
          month: 3,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 6,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
        {
          month: 12,
          precent: [
            {
              month: 1,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 2,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 3,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 4,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 5,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 6,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 7,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 8,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 9,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 10,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 11,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
            {
              month: 12,
              percentLow: 0,
              percentMid: 0,
              percentHigh: 0,
            },
          ],
          lowManCount: 0,
          lowManPrice: 0,
          midManCount: 0,
          midManPrice: 0,
          highManCount: 0,
          highManPrice: 0,
        },
      ],
      children: [
        {
          name: "test",
          order: 0,
          seqNo: "d54a4b14-f5b8-47a7-9817-d6f380122765",
          children: [],
          isHidden: false,
        },
      ],
    },
  ],
};

export const parentData = [
  { name: "UI/UX 전략", order: 0 },
  { name: "GUI 디자인", order: 1 },
  { name: "모션", order: 2 },
  { name: "프로토타입", order: 3 },
  { name: "개발", order: 4 },
];
